---
title: "Demand forecast"
output: html_document
---

```{r}
rm (list = ls(all = T))
options("width" = 200)

library(reshape)
library(ggplot2)
library(psych)
library(RCurl)
```

Set variables

```{r}
country <- "Germany" # Germany, France, Spain

forecast.price = 8
forecast.mkt.budget = 22000
forecast.catalog.pages = 0.5
forecast.comp.strength = 9
```

Get data

```{r}
url <- paste("https://raw.githubusercontent.com/intuitics/sample-demandforecasting/master/", paste(country, ".csv", sep = ""), sep = "")
data <- getURLContent(url, followlocation = T, binary = F, ssl.verifypeer = F)
data <- read.csv(textConnection(data))
```

Show descriptives

```{r}
data.summary <- describe(data)
data.summary <- data.summary[c("price", "marketing.budget", "catalog.pages", "competitor.strength", "total.cost", "revenue", "profit"), c("mean", "sd", "median", "min", "max", "range")]
data.summary$mean <- round(data.summary$mean, 2)
data.summary$sd <- round(data.summary$sd, 2)
data.summary
```

Show a single plot of the column defined by `plot.column.name`

```{r}
plot.column.name <- "profit" # cost, price, marketing.budget, catalog.pages, competitor.strength, demand, revenue, total.cost, profit
p <- ggplot(data, aes_string(x = "month", y = plot.column.name))
p <- p + geom_line(color = "blue") + xlab("Month") + ylab(plot.column.name)
p
```

Run linear regression

```{r}
model <- lm(demand ~ price + marketing.budget + catalog.pages + competitor.strength, data = data)
```

Show adjusted R-squared

```{r}
round(summary(model)[["adj.r.squared"]], 4)
```

Show coefficients

```{r}
coefs <- summary(model)[["coefficients"]]
coefs.table <- data.frame(Variable = row.names(coefs), Strength = cut(coefs[, 4], breaks = c(0, 0.01, 0.05, 0.1, 1), labels = c("Very strong", "Strong", "Medium", "Weak")), Coefficient = round(coefs[,1], 2), row.names = c())
coefs.table
```

Forecast the next month

```{r}
cost <- data$cost[1]

df <- data.frame(price = forecast.price, marketing.budget = forecast.mkt.budget, catalog.pages = forecast.catalog.pages, competitor.strength = forecast.comp.strength)

pred <- predict(model, df, interval = "prediction")
costs <- pred[,"fit"] * cost
revenue <- pred[,"fit"] * df$price
num.months <- nrow(data)

forecast <- data.frame(Month = c(num.months + 1), Demand.Avg = round(pred[,"fit"], 0), Demand.Upper = round(pred[,"upr"], 0), Demand.Lower = round(pred[,"lwr"], 0), Cost.Avg = round(costs, 0), Revenue.Avg = round(revenue, 0), Profit.Avg = round(revenue - costs, 0))
forecast
```

Forecast plot

```{r}
df <- tail(data[c("month", "demand", "profit")], 4)
df <- rbind(df, setNames(forecast[c("Month", "Demand.Avg", "Profit.Avg")], names(df)))

df <- melt(df, id.vars = c("month"))
p <- ggplot(df, aes(x = month, y = value))
p <- p + facet_grid(variable ~ ., scale="free")
p <- p + geom_line() + xlab("Month") + ylab("Value")
p
```